name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Crear archivo .env
        run: cp .env.example .env

      - name: Construir contenedores
        run: docker compose build

      - name: Levantar contenedores
        run: docker compose up -d

      - name: Ver contenedores activos
        run: docker compose ps

      - name: Esperar base de datos
        run: sleep 15

      - name: Instalar dependencias Composer
        run: docker compose exec -T app composer install

      - name: Generar APP_KEY
        run: docker compose exec -T app php artisan key:generate

      - name: Ejecutar migraciones
        run: docker compose exec -T app php artisan migrate --force

      - name: Limpiar cache Laravel
        run: docker compose exec -T app php artisan optimize:clear

      - name: Verificar Laravel
        run: docker compose exec -T app php artisan about
