name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Deploy en EC2 por SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.EC2_HOST }}
          username: ${{ vars.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            cd ~/colegio-aleman-system

            git pull origin main

            # El comando 'sed' busca la variable en tu .env y la reemplaza por el secreto encriptado de GitHub
            sed -i "s|^AWS_ACCESS_KEY_ID=.*|AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}|" .env
            sed -i "s|^AWS_SECRET_ACCESS_KEY=.*|AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}|" .env
            sed -i "s|^AWS_DEFAULT_REGION=.*|AWS_DEFAULT_REGION=us-east-1|" .env
            sed -i "s|^AWS_BUCKET=.*|AWS_BUCKET=${{ secrets.AWS_BUCKET }}|" .env
            sed -i "s|^AWS_USE_PATH_STYLE_ENDPOINT=.*|AWS_USE_PATH_STYLE_ENDPOINT=false|" .env

            sudo docker compose down

            sudo docker compose up -d --build

            sudo docker compose exec -T app composer install

            sudo docker compose exec -T app php artisan migrate --force

            sudo docker compose exec -T app php artisan optimize:clear
